pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_OPTIONS: '--max_old_space_size=4096'

steps:
# Install Node and Yarn
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Use Node.js 20'

- script: |
    corepack enable
    yarn install --frozen-lockfile
  workingDirectory: sample-app
  displayName: 'Install dependencies (Vite app)'

# Build the Vite app
- script: |
    yarn build
  workingDirectory: sample-app
  displayName: 'Build Vite App'

# Add test file (optional)
- script: |
    echo "This is run by CI/CD" > test-cicd.txt
  displayName: 'Write test file'

# Download GCP service account key
- task: DownloadSecureFile@1
  name: gcpKey
  inputs:
    secureFile: 'gcp-key.json'

# Authenticate and deploy using gcloud storage
- script: |
    echo "Activating service account..."
    gcloud auth activate-service-account --key-file=$(gcpKey.secureFilePath)

    echo "Setting GCP project..."
    gcloud config set project vatom-459619

    echo "Checking dist folder contents..."
    ls -la sample-app/dist || { echo "ERROR: dist folder missing"; exit 1; }

    if [ -d "sample-app/dist" ] && [ "$(ls -A sample-app/dist)" ]; then
      echo "Uploading build using gcloud storage cp..."
      gcloud storage cp -r --cache-control="no-cache" sample-app/dist/* gs://test-cicd-nix-20250624
    else
      echo "ERROR: dist folder is empty or not found"
      exit 1
    fi
  displayName: 'Deploy to GCP Bucket (gcloud storage)'
  failOnStderr: true
