pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_OPTIONS: '--max_old_space_size=4096'

steps:
# Install Node and Yarn
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Use Node.js 20'

- script: |
    corepack enable
    yarn install --frozen-lockfile
  workingDirectory: sample-app
  displayName: 'Install dependencies (Vite app)'

# Build the wallet app using Nx export
- script: |
    yarn nx export-web wallet
  workingDirectory: sample-app
  displayName: 'Export wallet web app'

# Download GCP service account key
- task: DownloadSecureFile@1
  name: gcpKey
  inputs:
    secureFile: 'gcp-key.json'

# Authenticate and deploy using gcloud storage cp
- script: |
    echo "Activating service account..."
    gcloud auth activate-service-account --key-file=$(gcpKey.secureFilePath)

    echo "Setting GCP project..."
    gcloud config set project vatom-459619

    echo "Checking exported build directory..."
    ls -la apps/wallet/web-build || { echo 'Build directory not found'; exit 1; }

    echo "Uploading with gcloud storage cp..."
    gcloud storage cp -r \
      --cache-control="no-cache" \
      apps/wallet/web-build/* gs://wallet-app-bucket-dev
  workingDirectory: sample-app
  displayName: 'Deploy wallet app to GCP bucket'
  failOnStderr: true
