trigger:
  branches:
    include:
      - main  # change if using a different default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_OPTIONS: '--max_old_space_size=4096'

steps:
# Install Node and Yarn
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Use Node.js 20'

- script: |
    corepack enable
    yarn install --frozen-lockfile
  workingDirectory: sample-app
  displayName: 'Install dependencies (Vite app)'

# Build the Vite app
- script: |
    yarn build
  workingDirectory: sample-app
  displayName: 'Build Vite App'

# Add test file (optional)
- script: |
    echo "This is run by CI/CD" > test-cicd.txt
  displayName: 'Write test file'

# Download GCP service account key
- task: DownloadSecureFile@1
  name: gcpKey
  inputs:
    secureFile: 'gcp-key.json'

# Authenticate and deploy to GCS
- script: |
    curl https://sdk.cloud.google.com | bash > /dev/null
    source $HOME/google-cloud-sdk/path.bash.inc
    gcloud auth activate-service-account --key-file=$(gcpKey.secureFilePath)
    gcloud config set project vatom-459619
    gsutil -m cp -r -h "Cache-Control:no-cache" sample-app/dist/* gs://test-cicd-nix-20250624
  displayName: 'Deploy to GCP Bucket'
